
export interface UnitContent {
  id: string;
  title: string;
  videoUrl: string;
  description: string;
  shortNote: string[];
  keyPoints: string[];
  animation: {
    title: string;
    flow: string[];
  };
  qa: {
    question: string;
    answer: string;
  }[];
  miniTask: {
    instruction: string;
    actionUrl?: string;
    actionPrompt?: string;
  };
  quiz: {
    question: string;
    options: string[];
    correctIndex: number;
  }[];
  project: {
    title: string;
    link: string;
  };
}

export interface ModuleContent {
  id: string;
  name: string;
  units: UnitContent[];
}

export const VIBECODING_CURRICULUM: ModuleContent[] = [
  {
    id: "module-1-web-basics",
    name: "Module 1 — Web Basics",
    units: [
      { id: "m1-1", title: "What is Internet", videoUrl: "https://www.youtube.com/watch?v=xe9S_XizQps", description: "Discover the global network.", shortNote: ["The Internet is a massive network of interconnected computers."], keyPoints: ["Global Network", "Servers and Clients", "ISP Connectivity"], animation: { title: "Packet Travel", flow: ["Data breaks into packets", "Routers find path", "Packets reassemble"] }, qa: [{ question: "What connects us?", answer: "The Internet" }], miniTask: { instruction: "Check your Public IP address." }, quiz: [{ question: "Internet is a:", options: ["Network", "Single PC", "CD Rom"], correctIndex: 0 }], project: { title: "Network Map", link: "Draw how your home connects to the net" } },
      { id: "m1-2", title: "How Websites Work", videoUrl: "https://www.youtube.com/watch?v=hJHvdBlSxug", description: "Understand the three pillars of the web.", shortNote: ["Websites are files read by your browser."], keyPoints: ["HTML Structure", "CSS Styling", "JS Logic"], animation: { title: "Loading Phase", flow: ["Browser gets file", "Parser starts", "UI appears"] }, qa: [{ question: "CSS is for?", answer: "Style" }], miniTask: { instruction: "View source of a website." }, quiz: [{ question: "Logic is in:", options: ["HTML", "JS", "CSS"], correctIndex: 1 }], project: { title: "Hello Web", link: "Create a simple HTML file" } },
      { id: "m1-3", title: "Client vs Server", videoUrl: "https://www.youtube.com/watch?v=7_LPdttKXPc", description: "The core communication model.", shortNote: ["Clients request, Servers respond."], keyPoints: ["Browsers are clients", "Data lives on servers"], animation: { title: "Communication", flow: ["Request sent", "Server looks up", "Data returned"] }, qa: [{ question: "Who serves data?", answer: "Server" }], miniTask: { instruction: "Describe a server in simple words." }, quiz: [{ question: "Is chrome a server?", options: ["No", "Yes"], correctIndex: 0 }], project: { title: "Role Play", link: "Explain client/server to a friend" } },
      { id: "m1-4", title: "HTTP Basics", videoUrl: "https://www.youtube.com/watch?v=iYM2zFP3Zn0", description: "The rules of web conversation.", shortNote: ["HTTP defines how messages are formatted."], keyPoints: ["Stateless protocol", "Safe communication"], animation: { title: "Protocol Check", flow: ["Connection init", "Handshake", "Sync"] }, qa: [{ question: "HTTP is?", answer: "Rules" }], miniTask: { instruction: "Search for HTTP meanings." }, quiz: [{ question: "Does HTTP wait?", options: ["No, it's stateless", "Yes"], correctIndex: 0 }], project: { title: "Rule Book", link: "Write 3 rules for your own app" } },
      { id: "m1-5", title: "HTTP Methods", videoUrl: "https://www.youtube.com/watch?v=q67tbeY8WAs", description: "Verbs that tell the server what to do.", shortNote: ["Methods move or change data."], keyPoints: ["GET (Read)", "POST (Create)", "PUT (Update)", "DELETE (Remove)"], animation: { title: "Actions", flow: ["Search = GET", "Post = POST", "Delete = DELETE"] }, qa: [{ question: "DELETE does?", answer: "Remove" }], miniTask: { instruction: "List 4 methods now." }, quiz: [{ question: "Create is:", options: ["GET", "POST", "DELETE"], correctIndex: 1 }], project: { title: "Verb Machine", link: "Build a list of app actions" } },
      { id: "m1-6", title: "Status Codes", videoUrl: "https://www.youtube.com/watch?v=XshFByPscT4", description: "Feedback from the digital world.", shortNote: ["Server sends codes to tell us if it worked."], keyPoints: ["200 = Success", "404 = Not Found", "500 = Error"], animation: { title: "Traffic Lights", flow: ["Green (200)", "Red (404/500)"] }, qa: [{ question: "Success code?", answer: "200" }], miniTask: { instruction: "Find a 404 page." }, quiz: [{ question: "Server error is:", options: ["200", "500"], correctIndex: 1 }], project: { title: "Error Catcher", link: "Design a 404 page" } },
      { id: "m1-7", title: "What is JSON", videoUrl: "https://www.youtube.com/watch?v=iiADhChRriM", description: "The simple language of data.", shortNote: ["JSON stands for JavaScript Object Notation."], keyPoints: ["Key-Value pairs", "Lightweight", "Universal format"], animation: { title: "Structure", flow: ["Object { }", "Key : Value"] }, qa: [{ question: "JSON is for?", answer: "Data" }], miniTask: { instruction: "Write { \"name\": \"me\" }." }, quiz: [{ question: "Which is JSON?", options: ["{ }", "< >", "[ ]"], correctIndex: 0 }], project: { title: "Data Card", link: "Create your JSON ID card" } },
      { id: "m1-8", title: "Request & Response", videoUrl: "https://www.youtube.com/watch?v=eesqK59rhGA", description: "The back-and-forth of the tech world.", shortNote: ["Every request gets a response."], keyPoints: ["Request Header", "Request Body", "Response Data"], animation: { title: "The Loop", flow: ["Req ->", "Wait", "<- Res"] }, qa: [{ question: "Req needs?", answer: "Res" }], miniTask: { instruction: "Explain req/res with a pizza analogy." }, quiz: [{ question: "Response contains:", options: ["Data", "Hardware"], correctIndex: 0 }], project: { title: "Conversation Map", link: "Map a request/response flow" } },
      { id: "m1-9", title: "What is API", videoUrl: "https://www.youtube.com/watch?v=s7wmiS2mSXY", description: "The bridges that connect software.", shortNote: ["APIs let apps talk to each other."], keyPoints: ["Data Bridge", "Software Interface", "Third-party connections"], animation: { title: "The Bridge", flow: ["App A -> API", "API -> App B"] }, qa: [{ question: "API is?", answer: "Bridge" }], miniTask: { instruction: "Search for 'Cat API'." }, quiz: [{ question: "API connecting?", options: ["Apps", "Batteries"], correctIndex: 0 }], project: { title: "API Hunter", link: "Find 3 cool public APIs" } },
      { id: "m1-10", title: "API Demo", videoUrl: "https://www.youtube.com/watch?v=Ove2Z9F-NMQ", description: "Real world impact of APIs.", shortNote: ["Watch an API in action right now."], keyPoints: ["Fetch call", "Data display", "Live updates"], animation: { title: "Live Action", flow: ["Click", "Load", "Show"] }, qa: [{ question: "Works?", answer: "Yes" }], miniTask: { instruction: "Fetch cat fact now." }, quiz: [{ question: "Is it live?", options: ["Yes", "No"], correctIndex: 0 }], project: { title: "First Interaction", link: "Connect your first API" } }
    ]
  },
  {
    id: "module-2-api-integration",
    name: "Module 2 — API Integration",
    units: [
      { id: "m2-1", title: "Fetch API", videoUrl: "https://www.youtube.com/watch?v=drK678A0f9k", description: "Learn to call APIs natively.", shortNote: ["Fetch is the built-in way to make network requests."], keyPoints: ["Native Browser API", "Promise-based", "Simple Syntax"], animation: { title: "Request Flow", flow: ["Fetch called", "Network request", "Promise resolve", "Data ready"] }, qa: [{ question: "Fetch is library?", answer: "No, it's native" }], miniTask: { instruction: "Call fetch on a text file." }, quiz: [{ question: "Fetch returns:", options: ["Promise", "String", "Number"], correctIndex: 0 }], project: { title: "Mini Fetch", link: "Build a button that fetches text" } },
      { id: "m2-2", title: "GET Request", videoUrl: "https://www.youtube.com/watch?v=fS6uV7_yXN0", description: "Fetching data the right way.", shortNote: ["GET is used to retrieve data from a server."], keyPoints: ["Read-only", "Query Params", "Cacheable"], animation: { title: "Get Cycle", flow: ["Ask for data", "Server finds", "Data returned"] }, qa: [{ question: "GET modifies data?", answer: "No" }], miniTask: { instruction: "Add a query param to a URL." }, quiz: [{ question: "GET is for:", options: ["Read", "Update"], correctIndex: 0 }], project: { title: "Data Reader", link: "Build a list that fetches from an API" } },
      { id: "m2-3", title: "POST Request", videoUrl: "https://www.youtube.com/watch?v=J8_vXGZlVlI", description: "Sending data to the cloud.", shortNote: ["POST is used to send data to create a resource."], keyPoints: ["Data in Body", "Secure transfer", "Server processing"], animation: { title: "Data Send", flow: ["Pack data", "Send to server", "Server saves"] }, qa: [{ question: "POST has body?", answer: "Yes" }], miniTask: { instruction: "Simulate a post call in JS." }, quiz: [{ question: "POST is for:", options: ["Create", "Read"], correctIndex: 0 }], project: { title: "Submit Form", link: "Build a contact form that logs data" } },
      { id: "m2-4", title: "API Response", videoUrl: "", description: "Understanding what the server says.", shortNote: ["Every request receives an object from the server."], keyPoints: ["Status code", "Headers", "JSON Payload"], animation: { title: "Response Unwrap", flow: ["Raw bits", "HTTP Check", "JSON Body"] }, qa: [{ question: "Response has data?", answer: "Yes" }], miniTask: { instruction: "Log a full response object." }, quiz: [{ question: "Data is usually:", options: ["JSON", "MP3"], correctIndex: 0 }], project: { title: "Response Inspector", link: "Build a tool to show API headers" } },
      { id: "m2-5", title: "Error Handling", videoUrl: "", description: "Making your app bulletproof.", shortNote: ["APIs can fail. You must handle the errors."], keyPoints: ["Try / Catch", "Network checks", "User feedback"], animation: { title: "Guard Logic", flow: ["Request sent", "Error occurs", "Catch runs", "Toast shows"] }, qa: [{ question: "Error handling needed?", answer: "Yes" }], miniTask: { instruction: "Write a try/catch block." }, quiz: [{ question: "Catch handles:", options: ["Errors", "Success"], correctIndex: 0 }], project: { title: "Safe Fetcher", link: "Build an app that shows 'Offline' on error" } },
      { id: "m2-6", title: "Axios", videoUrl: "", description: "The power of libraries.", shortNote: ["Axios is a popular library for API calls."], keyPoints: ["Auto JSON transform", "Easy interceptors", "Simpler syntax"], animation: { title: "Axios Boost", flow: ["Import Axios", "Config call", "Easy data"] }, qa: [{ question: "Axios is native?", answer: "No, it's a library" }], miniTask: { instruction: "Install axios (npm install)." }, quiz: [{ question: "Axios helps with:", options: ["Logic", "APIs"], correctIndex: 1 }], project: { title: "Axios Pro", link: "Rebuild your fetcher with Axios" } },
      { id: "m2-7", title: "Headers", videoUrl: "", description: "Metadata of the web.", shortNote: ["Headers contain info about the request or user."], keyPoints: ["Content-Type", "Authorization", "Custom headers"], animation: { title: "Envelope Info", flow: ["Address", "Stamp", "Metadata"] }, qa: [{ question: "Auth in headers?", answer: "Yes" }], miniTask: { instruction: "Check headers in network tab." }, quiz: [{ question: "Headers carry:", options: ["Metadata", "Large files"], correctIndex: 0 }], project: { title: "Header Studio", link: "Build an app to customize JSON headers" } },
      { id: "m2-8", title: "Loading State", videoUrl: "", description: "Improving the User Experience.", shortNote: ["Show a spinner while the API is fetching."], keyPoints: ["Visual feedback", "State management", "UX Design"], animation: { title: "Spinner", flow: ["Fetch start", "Show Loader", "Fetch end", "Hide Loader"] }, qa: [{ question: "Loading state user friendly?", answer: "Yes" }], miniTask: { instruction: "Show a simple loading text." }, quiz: [{ question: "When to show spinner?", options: ["During fetch", "After fetch"], correctIndex: 0 }], project: { title: "Smooth UI", link: "Add a skeleton loader to your app" } },
      { id: "m2-9", title: "UI Display", videoUrl: "", description: "Turning data into visuals.", shortNote: ["Map your JSON data into React components."], keyPoints: ["Lists / Grids", "Data binding", "Dynamic render"], animation: { title: "Data to Pixel", flow: ["JSON Array", "Loop/Map", "Cards render"] }, qa: [{ question: "Mapping needed?", answer: "Yes" }], miniTask: { instruction: "Map [1,2,3] to <li>." }, quiz: [{ question: "Component for data:", options: ["Map", "Filter"], correctIndex: 0 }], project: { title: "Data Grid", link: "Build a grid of user cards" } },
      { id: "m2-10", title: "API Practice", videoUrl: "", description: "The full integration loop.", shortNote: ["Build a complete flow from scratch."], keyPoints: ["Design", "Fetch", "Display"], animation: { title: "Master Loop", flow: ["Think", "Code", "Vibe"] }, qa: [{ question: "Ready?", answer: "Always" }], miniTask: { instruction: "Build a 1-page mini app." }, quiz: [{ question: "Integration complete?", options: ["Yes", "No"], correctIndex: 0 }], project: { title: "Weather Hub", link: "Build a multi-city weather app" } }
    ]
  },
  {
    id: "module-3-auth",
    name: "Module 3 — Authentication",
    units: [
      { id: "m3-1", title: "What is Auth", videoUrl: "https://www.youtube.com/watch?v=2v-pG_V7-Uo", description: "The gatekeeper of your app.", shortNote: ["Authentication checks if you are who you say you are."], keyPoints: ["Identity", "Protection", "User sessions"], animation: { title: "ID Check", flow: ["Who are you?", "Check DB", "Verified"] }, qa: [{ question: "Auth means?", answer: "Identity" }], miniTask: { instruction: "Login to your favorite app." }, quiz: [{ question: "Is Auth needed?", options: ["Yes", "No"], correctIndex: 0 }], project: { title: "The Gate", link: "Design a login sketch" } },
      { id: "m3-2", title: "Login & Signup", videoUrl: "https://www.youtube.com/watch?v=SLjpZozE_M8", description: "The entry points for users.", shortNote: ["Signup creates the user, Login verifies them."], keyPoints: ["Forms", "Input validation", "Submit logic"], animation: { title: "Form Flow", flow: ["Type name", "Type pass", "Submit"] }, qa: [{ question: "Signup creates?", answer: "User" }], miniTask: { instruction: "Describe a signup form." }, quiz: [{ question: "Signup is for:", options: ["Old users", "New users"], correctIndex: 1 }], project: { title: "Form Builder", link: "Build a login form in HTML" } },
      { id: "m3-3", title: "Password Basics", videoUrl: "https://www.youtube.com/watch?v=8ZtInClXe1Q", description: "Keeping secrets safe.", shortNote: ["Never store passwords in plain text."], keyPoints: ["Hashing", "Encryption", "Security"], animation: { title: "Hide Secrets", flow: ["Password", "Hash function", "Unreadable text"] }, qa: [{ question: "Store plain?", answer: "No" }], miniTask: { instruction: "Search for 'Password Hashing'." }, quiz: [{ question: "Hash is:", options: ["Unreadable", "Plain"], correctIndex: 0 }], project: { title: "Secret Safe", link: "Explain hashing in 3 lines" } },
      { id: "m3-4", title: "JWT", videoUrl: "", description: "The industry standard for tokens.", shortNote: ["JSON Web Tokens are portable ID cards."], keyPoints: ["Secret Key", "Payload", "Secure transfer"], animation: { title: "Token Card", flow: ["Data", "Signed", "Token created"] }, qa: [{ question: "JWT is?", answer: "Token" }], miniTask: { instruction: "Visit jwt.io." }, quiz: [{ question: "JWT stands for:", options: ["JSON Web Token", "Java Tool"], correctIndex: 0 }], project: { title: "ID Card", link: "Describe what's in a token" } },
      { id: "m3-5", title: "Token Flow", videoUrl: "", description: "How tokens move in your app.", shortNote: ["Token is sent with every request after login."], keyPoints: ["Headers", "Storage", "Verification"], animation: { title: "On the move", flow: ["Login", "Get Token", "Send with every call"] }, qa: [{ question: "Sent in?", answer: "Headers" }], miniTask: { instruction: "Locate tokens in browser dev tools." }, quiz: [{ question: "Stored in:", options: ["Browser", "Keyboard"], correctIndex: 0 }], project: { title: "Flow Chart", link: "Map the token lifecycle" } },
      { id: "m3-6", title: "Firebase Auth", videoUrl: "", description: "The easy way to do Auth.", shortNote: ["Firebase handles the backend of Auth for you."], keyPoints: ["Quick setup", "Social logins", "Managed users"], animation: { title: "Auto Pilot", flow: ["Social click", "Firebase verifies", "Login done"] }, qa: [{ question: "Firebase is?", answer: "Service" }], miniTask: { instruction: "Create a Firebase project." }, quiz: [{ question: "Does it help?", options: ["Yes", "No"], correctIndex: 0 }], project: { title: "Rapid Auth", link: "Setup Firebase Auth node" } },
      { id: "m3-7", title: "Protected Routes", videoUrl: "", description: "Gating your content.", shortNote: ["Only logged in users can see these pages."], keyPoints: ["Authentication Gate", "User state check", "Redirects"], animation: { title: "Member Only", flow: ["User clicks", "Check Token", "Access Page"] }, qa: [{ question: "Gate for?", answer: "Pages" }], miniTask: { instruction: "Identify a members page online." }, quiz: [{ question: "Secure?", options: ["Required", "Optional"], correctIndex: 0 }], project: { title: "Room Gate", link: "Design a private dashboard layout" } },
      { id: "m3-8", title: "Logout", videoUrl: "", description: "Closing the session safely.", shortNote: ["Logout clears the token and ends the session."], keyPoints: ["Clear storage", "State reset", "Security cleanup"], animation: { title: "Goodbye", flow: ["Click Logout", "Token Deleted", "Redirect Home"] }, qa: [{ question: "Clears?", answer: "Token" }], miniTask: { instruction: "Find the logout button on this site." }, quiz: [{ question: "Essential?", options: ["Yes", "No"], correctIndex: 0 }], project: { title: "Clean Exit", link: "Explain why logout matters" } },
      { id: "m3-9", title: "Roles", videoUrl: "", description: "Managing permissions.", shortNote: ["Not all users have the same power."], keyPoints: ["Admin vs User", "Permissions", "Authorisation"], animation: { title: "Power Levels", flow: ["Admin (Delete/Edit)", "User (Read)"] }, qa: [{ question: "Admin can?", answer: "Manage" }], miniTask: { instruction: "List 2 roles in a school app." }, quiz: [{ question: "Is Admin a role?", options: ["Yes", "No"], correctIndex: 0 }], project: { title: "Role Rules", link: "Define permissions for 3 roles" } },
      { id: "m3-10", title: "Auth Flow", videoUrl: "", description: "The complete loop.", shortNote: ["From login to logout—the full lifecycle."], keyPoints: ["End-to-end", "User Journey", "Secure Loop"], animation: { title: "The Loop", flow: ["Signup", "Login", "Access", "Logout"] }, qa: [{ question: "Complete?", answer: "Yes" }], miniTask: { instruction: "Summarize the 10 steps." }, quiz: [{ question: "Know the flow?", options: ["Yes", "No"], correctIndex: 0 }], project: { title: "The System", link: "Build the full auth journey" } }
    ]
  },
  {
    id: "module-4-db",
    name: "Module 4 — Database",
    units: [
      { id: "m4-1", title: "Database Intro", videoUrl: "https://www.youtube.com/watch?v=Tk1t3WKK-nQ", description: "Where your data lives.", shortNote: ["Databases provide persistent storage for your app."], keyPoints: ["Storage", "Persistence", "Data integrity"], animation: { title: "Save Loop", flow: ["App -> Data", "DB -> Save", "DB -> Confirm"] }, qa: [{ question: "DB stores?", answer: "Data" }], miniTask: { instruction: "List 3 items you'd store in a DB." }, quiz: [{ question: "Persistence means:", options: ["Long term", "Short term"], correctIndex: 0 }], project: { title: "Data Wishlist", link: "Define your app's data schema" } },
      { id: "m4-2", title: "SQL vs NoSQL", videoUrl: "https://www.youtube.com/watch?v=ZS_kXvOeQ5Y", description: "Choosing the right storage format.", shortNote: ["SQL is structured (tables), NoSQL is flexible (documents)."], keyPoints: ["Structured vs Unstructured", "Scaling", "Schema"], animation: { title: "Formats", flow: ["Table (Row/Col)", "Document {Key/Val}"] }, qa: [{ question: "NoSQL is?", answer: "Flexible" }], miniTask: { instruction: "Describe a table in 2 words." }, quiz: [{ question: "Firestore is:", options: ["NoSQL", "SQL"], correctIndex: 0 }], project: { title: "Storage Choice", link: "Argue for NoSQL in a chat app" } },
      { id: "m4-3", title: "Tables", videoUrl: "https://www.youtube.com/watch?v=W2Z79930fHY", description: "The foundation of relational data.", shortNote: ["Rows and Columns store related pieces of info."], keyPoints: ["Primary Keys", "Relationships", "Fixed Schema"], animation: { title: "Row Fill", flow: ["ID 1", "Name: Sach", "Joined: Today"] }, qa: [{ question: "Tables have?", answer: "Rows" }], miniTask: { instruction: "Sketch a table for 'Library'." }, quiz: [{ question: "Is a cell part of a table?", options: ["Yes", "No"], correctIndex: 0 }], project: { title: "Table Architect", link: "Define a 5-column table for Orders" } },
      { id: "m4-4", title: "Documents", videoUrl: "", description: "The power of JSON-like storage.", shortNote: ["Documents allow nested data and fast reads."], keyPoints: ["Collections", "Fields", "No strict schema"], animation: { title: "Doc Nesting", flow: ["User { }", "Orders [ ]", "Profile { }"] }, qa: [{ question: "Nested data ok?", answer: "Yes" }], miniTask: { instruction: "Write a document for a 'Product'." }, quiz: [{ question: "Documents are in:", options: ["NoSQL", "SQL"], correctIndex: 0 }], project: { title: "Document Studio", link: "Create a complex JSON document" } },
      { id: "m4-5", title: "CRUD", videoUrl: "", description: "The four pillars of data management.", shortNote: ["Every data interaction is Create, Read, Update, or Delete."], keyPoints: ["Core operations", "Data lifecycle", "Backend logic"], animation: { title: "CRUD Wheel", flow: ["C", "R", "U", "D"] }, qa: [{ question: "U means?", answer: "Update" }], miniTask: { instruction: "List CRUD examples for 'Post'." }, quiz: [{ question: "Read is:", options: ["Fetching", "Deleting"], correctIndex: 0 }], project: { title: "Action Tracker", link: "Identify CRUD ops in your favorite app" } },
      { id: "m4-6", title: "Insert", videoUrl: "", description: "Bringing data into the world.", shortNote: ["Inserting is adding a new record to the database."], keyPoints: ["Save", "ID creation", "Validation"], animation: { title: "The Drop", flow: ["Data ready", "Push to DB", "Record created"] }, qa: [{ question: "Insert creates?", answer: "Record" }], miniTask: { instruction: "Write an 'add' function name." }, quiz: [{ question: "Insert is:", options: ["Add", "Remove"], correctIndex: 0 }], project: { title: "Data Adder", link: "Build a form to insert a user" } },
      { id: "m4-7", title: "Read", videoUrl: "", description: "Retrieving your digital assets.", shortNote: ["Read queries data back to the UI."], keyPoints: ["Queries", "Filters", "Real-time updates"], animation: { title: "The Fetch", flow: ["Query sent", "DB match", "Data returned"] }, qa: [{ question: "Read = Fetch?", answer: "Yes" }], miniTask: { instruction: "Filter [1, 5, 10] > 5." }, quiz: [{ question: "Filtering happens in:", options: ["Read", "Create"], correctIndex: 0 }], project: { title: "Search Hub", link: "Build a search bar for your data" } },
      { id: "m4-8", title: "Update", videoUrl: "", description: "Modifying the existing state.", shortNote: ["Changing data that already exists in the DB."], keyPoints: ["Merge", "Overwrite", "Selective update"], animation: { title: "The Edit", flow: ["Find old", "Patch new", "Save current"] }, qa: [{ question: "Update changes?", answer: "Existsing" }], miniTask: { instruction: "Update 'name' to 'Vibe'." }, quiz: [{ question: "Change is:", options: ["Update", "Delete"], correctIndex: 0 }], project: { title: "Profile Editor", link: "Build a profile settings page" } },
      { id: "m4-9", title: "Delete", videoUrl: "", description: "Cleaning up the environment.", shortNote: ["Removing records permanently from storage."], keyPoints: ["Soft delete", "Hard delete", "Cleanup"], animation: { title: "The Wipe", flow: ["Target ID", "DB Remove", "Record Gone"] }, qa: [{ question: "Delete is final?", answer: "Usually" }], miniTask: { instruction: "Remove ID 5 from memory." }, quiz: [{ question: "Wiping is:", options: ["Delete", "Read"], correctIndex: 0 }], project: { title: "Trash Can", link: "Add a delete button to every record" } },
      { id: "m4-10", title: "Firestore", videoUrl: "", description: "Real-time NoSQL Mastery.", shortNote: ["Firestore is Google's high-perf real-time database."], keyPoints: ["Real-time sync", "Offline support", "Scalable"], animation: { title: "Live Sync", flow: ["DB Change", "Subscriber notified", "UI Updates"] }, qa: [{ question: "Firestore live?", answer: "Yes" }], miniTask: { instruction: "Enable Firestore in Firebase." }, quiz: [{ question: "Firestore is from:", options: ["Google/Firebase", "Amazon"], correctIndex: 0 }], project: { title: "Live Chat DB", link: "Connect a real-time message stream" } }
    ]
  },
  {
    id: "module-5-backend",
    name: "Module 5 — Backend",
    units: [
      { id: "m5-1", title: "Backend Intro", videoUrl: "", description: "The brain of the operation.", shortNote: ["Backend handles logic, security, and data storage."], keyPoints: ["Server-side", "Invisible logic", "Security layer"], animation: { title: "Hidden Logic", flow: ["App Request", "Backend brain", "DB Query", "Result"] }, qa: [{ question: "Backend is UI?", answer: "No, logic" }], miniTask: { instruction: "Name 1 backend framework." }, quiz: [{ question: "Backend is:", options: ["Invisible", "Visible"], correctIndex: 0 }], project: { title: "Logic Plan", link: "Map your app's hidden features" } },
      { id: "m5-2", title: "Node.js", videoUrl: "", description: "Javascript on the server.", shortNote: ["Node allowed JS to run outside the browser."], keyPoints: ["V8 Engine", "NPM Ecosystem", "Fast execution"], animation: { title: "Runtime", flow: ["JS File", "Node Engine", "Server Start"] }, qa: [{ question: "Node runs JS?", answer: "Yes" }], miniTask: { instruction: "Check node -v in terminal." }, quiz: [{ question: "Node is for:", options: ["Server", "Styles"], correctIndex: 0 }], project: { title: "Script Master", link: "Write a simple node script" } },
      { id: "m5-3", title: "Express", videoUrl: "", description: "The web framework for Node.", shortNote: ["Express makes building APIs fast and simple."], keyPoints: ["Routing", "Middleware", "HTTP handling"], animation: { title: "Fast API", flow: ["Import Express", "App Use", "Listen Port"] }, qa: [{ question: "Express handles routes?", answer: "Yes" }], miniTask: { instruction: "Define an express app variable." }, quiz: [{ question: "Express is for:", options: ["Framework", "Hardware"], correctIndex: 0 }], project: { title: "Server Start", link: "Launch an express server" } },
      { id: "m5-4", title: "Routes", videoUrl: "", description: "Defining the paths to data.", shortNote: ["Routes map URLs to specific functions in your backend."], keyPoints: ["Endpoints", "URL Params", "Route handlers"], animation: { title: "Map Logic", flow: ["/users -> Get Users", "/posts -> Get Posts"] }, qa: [{ question: "Routes map URLs?", answer: "Yes" }], miniTask: { instruction: "Write 3 route paths." }, quiz: [{ question: "Is /login a route?", options: ["Yes", "No"], correctIndex: 0 }], project: { title: "Route Map", link: "Define 10 endpoints for your app" } },
      { id: "m5-5", title: "Controllers", videoUrl: "", description: "The logic handlers.", shortNote: ["Controllers contain the actual logic for your routes."], keyPoints: ["Separation of concerns", "Functions", "Request/Response handle"], animation: { title: "Brain Hub", flow: ["Route calls", "Controller runs", "Logic finish"] }, qa: [{ question: "Controllers handle logic?", answer: "Yes" }], miniTask: { instruction: "Write a function name 'getUser'." }, quiz: [{ question: "Is controller visible?", options: ["No", "Yes"], correctIndex: 0 }], project: { title: "Logic Hub", link: "Write logic for 'Create Post'" } },
      { id: "m5-6", title: "Middleware", videoUrl: "", description: "The interceptors.", shortNote: ["Middleware runs code between the request and response."], keyPoints: ["Authentication", "Logging", "Validation"], animation: { title: "Interpreting", flow: ["Req ->", "Middleware", "-> Controller"] }, qa: [{ question: "Middleware runs before?", answer: "Yes" }], miniTask: { instruction: "Search for 'Express Logger'." }, quiz: [{ question: "Middleware can block?", options: ["Yes", "No"], correctIndex: 0 }], project: { title: "Guard System", link: "Add an 'auth guard' middleware" } },
      { id: "m5-7", title: "Request", videoUrl: "", description: "Handling user data.", shortNote: ["Req object contains everything the user sent."], keyPoints: ["req.body", "req.params", "req.query"], animation: { title: "Payload Load", flow: ["User data", "Backend unpack", "Controller use"] }, qa: [{ question: "Body in request?", answer: "Yes" }], miniTask: { instruction: "Get 'id' from req.params." }, quiz: [{ question: "Request comes from:", options: ["Client", "Database"], correctIndex: 0 }], project: { title: "Input Logger", link: "Log every user request" } },
      { id: "m5-8", title: "Response", videoUrl: "", description: "Talking back to the client.", shortNote: ["Res object is used to send data back."], keyPoints: ["res.json()", "res.status()", "Finality"], animation: { title: "Reply Flow", flow: ["Logic done", "Prepare JSON", "Send res"] }, qa: [{ question: "res.json() sends data?", answer: "Yes" }], miniTask: { instruction: "Send a {success: true}." }, quiz: [{ question: "Response is for:", options: ["Client", "Hardware"], correctIndex: 0 }], project: { title: "Reply Machine", link: "Build custom response messages" } },
      { id: "m5-9", title: "Errors", videoUrl: "", description: "Managing the unexpected.", shortNote: ["Global error handlers prevent server crashes."], keyPoints: ["Try / Catch", "Error Middleware", "User messages"], animation: { title: "Safe Net", flow: ["Error!", "Catcher runs", "Safe message"] }, qa: [{ question: "Errors crash servers?", answer: "If not handled" }], miniTask: { instruction: "Throw a new Error()." }, quiz: [{ question: "Handle errors with:", options: ["Try/Catch", "Ignore"], correctIndex: 0 }], project: { title: "Safety Mesh", link: "Build a global error handler" } },
      { id: "m5-10", title: "API Flow", videoUrl: "", description: "The full backend loop.", shortNote: ["Connect Node, Express, and DB in one flow."], keyPoints: ["Lifecycle", "Integration", "Production ready"], animation: { title: "Full Loop", flow: ["Think", "Code", "Server Up"] }, qa: [{ question: "Backend done?", answer: "Yes" }], miniTask: { instruction: "Explain backend in 10 words." }, quiz: [{ question: "Is it the heart?", options: ["Yes", "No"], correctIndex: 0 }], project: { title: "Master API", link: "Build a full Todo List backend" } }
    ]
  },
  {
    id: "module-6-testing",
    name: "Module 6 — Testing",
    units: [
      { id: "m6-1", title: "Debugging", videoUrl: "", description: "The art of finding bugs.", shortNote: ["Debugging is identifying and removing errors."], keyPoints: ["Patience", "Logic", "Tools"], animation: { title: "Find Bug", flow: ["Error seen", "Search code", "Fix found"] }, qa: [{ question: "Debug = fix?", answer: "Yes" }], miniTask: { instruction: "Deliberately cause a typo." }, quiz: [{ question: "Is debug fun?", options: ["Yes", "No"], correctIndex: 0 }], project: { title: "Bug Hunter", link: "List 5 bugs you found today" } },
      { id: "m6-2", title: "Console", videoUrl: "", description: "The developer's best friend.", shortNote: ["Console.log is the window into your code's brain."], keyPoints: ["log", "error", "warn"], animation: { title: "Brain Dump", flow: ["Variable", "Console", "Visible Value"] }, qa: [{ question: "console.log works?", answer: "Yes" }], miniTask: { instruction: "Log your name." }, quiz: [{ question: "Print to console:", options: ["log", "print"], correctIndex: 0 }], project: { title: "Log Studio", link: "Log a complex object tree" } },
      { id: "m6-3", title: "DevTools", videoUrl: "", description: "The browser's command center.", shortNote: ["Browser DevTools let you inspect every pixel and request."], keyPoints: ["Elements", "Network", "Application"], animation: { title: "Inspect Mode", flow: ["Right click", "Inspect", "Magic"] }, qa: [{ question: "DevTools built-in?", answer: "Yes" }], miniTask: { instruction: "Change <h1> text in DevTools." }, quiz: [{ question: "Shortcut key:", options: ["F12", "F1"], correctIndex: 0 }], project: { title: "Visual Hack", link: "Change a website's theme in DevTools" } },
      { id: "m6-4", title: "Network", videoUrl: "", description: "Seeing the data flow.", shortNote: ["Monitor every API call and asset download."], keyPoints: ["Waterfall", "Timings", "Status"], animation: { title: "Traffic Watch", flow: ["Req Start", "Loading Bar", "Finished"] }, qa: [{ question: "Network shows APIs?", answer: "Yes" }], miniTask: { instruction: "Filter 'Fetch/XHR' in Network tab." }, quiz: [{ question: "Is speed visible?", options: ["Yes", "No"], correctIndex: 0 }], project: { title: "Traffic Report", link: "List the 5 slowest calls on a site" } },
      { id: "m6-5", title: "Errors", videoUrl: "", description: "The red text of growth.", shortNote: ["Learn to read stack traces and error messages."], keyPoints: ["Syntax Error", "Reference Error", "Stack Trace"], animation: { title: "Trace Back", flow: ["Error!", "Line Num", "Fix Code"] }, qa: [{ question: "Read stack trace?", answer: "Yes" }], miniTask: { instruction: "Read a 'ReferenceError'." }, quiz: [{ question: "Red text means:", options: ["Error", "Success"], correctIndex: 0 }], project: { title: "Error Log", link: "Translate 3 complex errors" } },
      { id: "m6-6", title: "Fix Bugs", videoUrl: "", description: "The satisfaction of a fix.", shortNote: ["Apply fixes systematically and test afterward."], keyPoints: ["Isolation", "Patch", "Validate"], animation: { title: "Repair", flow: ["Broken", "Fixed", "Working"] }, qa: [{ question: "Fixing is easy?", answer: "With logic" }], miniTask: { instruction: "Fix the typo you made earlier." }, quiz: [{ question: "Fixed?", options: ["Yes", "No"], correctIndex: 0 }], project: { title: "Repair Shop", link: "Fix a broken code snippet" } },
      { id: "m6-7", title: "Postman", videoUrl: "", description: "Mastering API testing.", shortNote: ["Postman is a tool to test APIs without a frontend."], keyPoints: ["Collections", "Variables", "Environments"], animation: { title: "API Lab", flow: ["Type URL", "Choose Method", "Get JSON"] }, qa: [{ question: "Postman for APIs?", answer: "Yes" }], miniTask: { instruction: "Download Postman." }, quiz: [{ question: "Postman helps:", options: ["Testing", "Styling"], correctIndex: 0 }], project: { title: "API Lab", link: "Document 5 endpoints in Postman" } },
      { id: "m6-8", title: "API Test", videoUrl: "", description: "Verifying your logic.", shortNote: ["Test success, fail, and edge cases for every API."], keyPoints: ["Edge cases", "Automation", "Validation"], animation: { title: "Stresser", flow: ["Big data", "Small data", "No data"] }, qa: [{ question: "Test edge cases?", answer: "Yes" }], miniTask: { instruction: "Test an API with empty body." }, quiz: [{ question: "Essential?", options: ["Yes", "No"], correctIndex: 0 }], project: { title: "Test Suite", link: "Build a test doc for your backend" } },
      { id: "m6-9", title: "Common Issues", videoUrl: "", description: "Avoid the standard traps.", shortNote: ["Learn about CORS, Auth failures, and Data mismatches."], keyPoints: ["CORS", "Missing Env", "JSON parse"], animation: { title: "Trap Avoidance", flow: ["Mistake", "Learn", "Pro"] }, qa: [{ question: "CORS common?", answer: "Yes" }], miniTask: { instruction: "Search for 'CORS error fix'." }, quiz: [{ question: "CORS is about:", options: ["Domains", "Colors"], correctIndex: 0 }], project: { title: "Gotcha List", link: "Write a list of 5 common errors" } },
      { id: "m6-10", title: "Debug Flow", videoUrl: "", description: "The expert workflow.", shortNote: ["A systematic approach to solving any tech issue."], keyPoints: ["Systematic", "Logical", "Mastery"], animation: { title: "Expert Loop", flow: ["Observe", "Hypothesize", "Fix"] }, qa: [{ question: "Expert?", answer: "Soon" }], miniTask: { instruction: "Summarize debugging in 3 steps." }, quiz: [{ question: "Ready to fix?", options: ["Yes", "No"], correctIndex: 0 }], project: { title: "Professional Debugger", link: "Build a bug tracking dashboard" } }
    ]
  },
  {
    id: "module-7-uiux",
    name: "Module 7 — UI/UX",
    units: [
      { id: "m7-1", title: "UI Basics", videoUrl: "", description: "The face of your app.", shortNote: ["User Interface is how the app looks and interacts."], keyPoints: ["Visuals", "Interactions", "Aesthetics"], animation: { title: "Look & Feel", flow: ["Colors", "Shapes", "Final UI"] }, qa: [{ question: "UI is look?", answer: "Yes" }], miniTask: { instruction: "Name your favorite UI app." }, quiz: [{ question: "UI means:", options: ["Interface", "Internet"], correctIndex: 0 }], project: { title: "UI Moodboard", link: "Collect 5 beautiful UI screens" } },
      { id: "m7-2", title: "UX Basics", videoUrl: "", description: "The soul of your app.", shortNote: ["User Experience is how the user feels and navigates."], keyPoints: ["Flow", "Retention", "Simplicity"], animation: { title: "The Flow", flow: ["Easy path", "Fast win", "Happy user"] }, qa: [{ question: "UX is feel?", answer: "Yes" }], miniTask: { instruction: "Describe a 'bad' experience." }, quiz: [{ question: "UX means:", options: ["Experience", "Exception"], correctIndex: 0 }], project: { title: "UX Audit", link: "Fix one frustrating flow in an app" } },
      { id: "m7-3", title: "Layout", videoUrl: "", description: "Structuring the screen.", shortNote: ["Layout is how elements are positioned on the page."], keyPoints: ["Grids", "Flexbox", "Alignment"], animation: { title: "The Grid", flow: ["Header", "Content", "Sidebar"] }, qa: [{ question: "Grids help?", answer: "Yes" }], miniTask: { instruction: "Sketch a 3-column grid." }, quiz: [{ question: "Is header a layout part?", options: ["Yes", "No"], correctIndex: 0 }], project: { title: "Wireframe", link: "Draw a layout for a Portfolio" } },
      { id: "m7-4", title: "Spacing", videoUrl: "", description: "The breathing room.", shortNote: ["Proper white space makes UI look high-end and clean."], keyPoints: ["Padding / Margin", "Visual hierarchy", "Breathing room"], animation: { title: "Breathe", flow: ["Clusters", "Add space", "Clean"] }, qa: [{ question: "Space is good?", answer: "Yes" }], miniTask: { instruction: "Set 20px padding in code." }, quiz: [{ question: "Spacing helps:", options: ["Readability", "Speed"], correctIndex: 0 }], project: { title: "Clean Card", link: "Redesign a card with better spacing" } },
      { id: "m7-5", title: "Colors", videoUrl: "", description: "Defining the vibe.", shortNote: ["Colors evoke emotions and guide the user's attention."], keyPoints: ["Contrast", "Palette", "Brand Vibe"], animation: { title: "Palette", flow: ["Primary", "Secondary", "Contrast"] }, qa: [{ question: "Contrast matters?", answer: "Yes" }], miniTask: { instruction: "Pick a 'premium' color." }, quiz: [{ question: "Accessible colors:", options: ["Contrast well", "Are bright"], correctIndex: 0 }], project: { title: "Vibe Palette", link: "Create a 5-color aesthetic palette" } },
      { id: "m7-6", title: "Typography", videoUrl: "", description: "The voice of the brand.", shortNote: ["Choosing the right font changes the entire 'vibe' of the site."], keyPoints: ["Hierarchy", "Font families", "Readability"], animation: { title: "The Voice", flow: ["Bold Header", "Light Body", "Action Font"] }, qa: [{ question: "Reading easy?", answer: "With good fonts" }], miniTask: { instruction: "Compare Serif vs Sans-serif." }, quiz: [{ question: "Hierarchy helps:", options: ["Scannability", "Weight"], correctIndex: 0 }], project: { title: "Typographic Scale", link: "Define H1 to P sizes for your app" } },
      { id: "m7-7", title: "Components", videoUrl: "", description: "Building blocks of UI.", shortNote: ["Reusable buttons, inputs, and cards save time and ensure consistency."], keyPoints: ["Buttons", "Modals", "Inputs"], animation: { title: "Assembly", flow: ["One button", "Many parts", "Full Page"] }, qa: [{ question: "Components reusable?", answer: "Yes" }], miniTask: { instruction: "Build a single Button component." }, quiz: [{ question: "Reuse is key?", options: ["Yes", "No"], correctIndex: 0 }], project: { title: "Kit Builder", link: "Design 5 reusable UI components" } },
      { id: "m7-8", title: "Responsive", videoUrl: "", description: "UI for every screen.", shortNote: ["Your app must look great on Phone, Tablet, and Desktop."], keyPoints: ["Media queries", "Breakpoints", "Mobile-first"], animation: { title: "Flex", flow: ["Desktop", "Tablet", "Mobile"] }, qa: [{ question: "Mobile first?", answer: "Best practice" }], miniTask: { instruction: "Resize your browser window." }, quiz: [{ question: "Responsive means:", options: ["Fits all screens", "Fast"], correctIndex: 0 }], project: { title: "Device Switcher", link: "Make your dashboard mobile-responsive" } },
      { id: "m7-9", title: "Mobile", videoUrl: "", description: "Mastering the small screen.", shortNote: ["Mobile-first design focuses on the most essential content."], keyPoints: ["Touch size", "Minimalism", "Scrolling"], animation: { title: "Thumb Zone", flow: ["Top bar", "Main scroll", "Bottom nav"] }, qa: [{ question: "Touch needs space?", answer: "Yes" }], miniTask: { instruction: "Check a website on your phone." }, quiz: [{ question: "Navigation usually at:", options: ["Bottom/Top", "Sides"], correctIndex: 0 }], project: { title: "App Shell", link: "Design a mobile-only app shell" } },
      { id: "m7-10", title: "Design Rules", videoUrl: "", description: "The expert polish.", shortNote: ["Apply consistency, hierarchy, and balance to reach mastery."], keyPoints: ["Consistency", "Balance", "Hierarchy"], animation: { title: "Master Polish", flow: ["Basic", "Styled", "Premium"] }, qa: [{ question: "Polish needed?", answer: "Always" }], miniTask: { instruction: "List 1 design rule." }, quiz: [{ question: "Zero Errors?", options: ["Yes", "No"], correctIndex: 0 }], project: { title: "Mastershot Dashboard", link: "Finalize your flagship app UI" } }
    ]
  }
];
